a = list(("apple", "banana", "cherry"))
b = tuple(("apple", "banana", "cherry"))	
c = range(6)
d = dict(name="John", age=36)	
e = set(("apple", "banana", "cherry"))	
f = frozenset(("apple", "banana", "cherry"))	
g = bool(5)	
h = bytes(5)	
i = bytearray(5)	
j = memoryview(bytes(5))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))